
version: '3'

services:

  fcrepo:
    build: ./fcrepo
    volumes:
      - fedora-data:/fedora-data
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_COOKIE_NAME=${JWT_COOKIE_NAME}

  server:
    build: ./server
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_TTL=${JWT_TTL}
      - JWT_COOKIE_NAME=${JWT_COOKIE_NAME}

  proxy:
    build: ./proxy
    ports:
      - 3000:80


volumes:
  fedora-data:
    driver: local