version: '3'

###
# Demo Fin Server from deployed DockerHub container images
###
services:

  ###
  # Font End NodeJS Application Server
  ###
  server:
    image: ucdlib/fin-server:master
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - FIN_URL=${FIN_URL}
      - FIN_ENV=dev
      - FIN_ALLOW_ORIGINS=localhost:8081
    volumes:
      - ../../services/default-services.js:/etc/fin/default-services.js
      - ../webapp-service-account.json:/etc/fin/webapp-service-account.json
      - ../../server/backups:/fcrepo-backups
      - ../../server/default-transforms:/etc/fin/transforms
    ports:
      - 3000:3001
    depends_on:
      - fcrepo
      - redis
      - elasticsearch

  ###
  # Fedora Repository
  ###
  fcrepo:
    image: ucdlib/fin-fcrepo:master
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_VERBOSE=${JWT_VERBOSE}
      - FIN_URL=${FIN_URL}
    volumes:
      - fedora-data:/var/lib/jetty/fedora-data
      - ./backups:/var/lib/jetty/fcrepo-backups

  ###
  # Session, admin store
  ###
  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data
    depends_on:
      - fcrepo

  ###
  # UC DAMS Client UI
  ###
  ucd-lib-client:
    image: ucdlib/fin-ucd-lib-client:master
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - FIN_URL=${FIN_URL}
    depends_on:
      - elasticsearch

  tesseract:
    image: ucdlib/fin-tesseract-service:master
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - FIN_URL=${FIN_URL}
    depends_on:
      - server

  ###
  # Search
  ###
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ../elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    depends_on:
      - fcrepo

  ###
  # Trusted Proxy for Services
  ###
  trustedproxy:
    image: ucdlib/fin-trusted-proxy:master
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_TTL=${JWT_TTL}
    depends_on:
      - fcrepo

  ###
  # IIIF Service
  ###
  loris:
    image: ucdlib/fin-loris-service:master
    depends_on:
      - fcrepo
    volumes:
      - loris-data:/usr/local/share/images/loris
      - ../../services/loris/loris2.conf:/opt/loris/etc/loris2.conf
      - ../../services/loris/start.py:/opt/loris/loris/start.py
  ###
  # ES Indexer
  ###
  essync:
    image: ucdlib/fin-essync-service:master
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - FIN_URL=${FIN_URL}
    depends_on:
      - server
  
  cas:
    image: ucdlib/fin-cas-service:master
    volumes:
      - ../webapp-service-account.json:/etc/fin/webapp-service-account.json
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - FIN_URL=${FIN_URL}
      - CAS_URL=https://ssodev.ucdavis.edu/cas
    depends_on:
      - server
    command: node service

###
# Docker data volumes
###
volumes:
  fedora-data:
    driver: local
  fedora-serialized-data:
    driver: local
  es-data:
    driver: local
  redis-data:
    driver: local
  loris-data:
    driver: local
  loris-cache:
    driver: local