
version: '2'

###
# Prod
###
services:

  ###
  # Font End NodeJS Application Server & Proxy
  ###
  server:
    build: ../../server
    volumes:
      - ../services.js:/etc/dams/services.js
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_TTL=${JWT_TTL}
      - JWT_COOKIE_NAME=${JWT_COOKIE_NAME}
      - DAMS_URL=${DAMS_URL}
      - DAMS_ENV=prod
    depends_on:
      - fcrepo
      - elasticsearch
      - redis
    ports:
      - 3000:3001

  ###
  # Fedora Repository
  ###
  fcrepo:
    build: ../../fcrepo
    volumes:
      - fedora-data:/var/lib/jetty/fedora-data
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_COOKIE_NAME=${JWT_COOKIE_NAME}
      - JWT_VERBOSE=${JWT_VERBOSE}
      - DAMS_URL=${DAMS_URL}

  ###
  # Search
  ###
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ../elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    depends_on:
      - fcrepo

  ###
  # Session, local user and role store
  ###
  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data
    depends_on:
      - fcrepo  

  ###
  # Trusted Proxy for Services
  ###
  trustedproxy:
    build: ../../trusted-proxy
    depends_on:
      - fcrepo
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_TTL=${JWT_TTL}

  ###
  # API Extension Services
  ###

  # iiif server
  loris:
    build: ../../loris
    depends_on:
      - fcrepo

  # elastic search indexer
  essync:
    build: ../../activemq/essync
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_TTL=${JWT_TTL}
      - DAMS_URL=${DAMS_URL}
    depends_on:
      - server
      - fcrepo
      - elasticsearch
    command: node service

  # file system serialization
  serialization:
    build: ../../activemq/serialization
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_TTL=${JWT_TTL}
      - DAMS_URL=${DAMS_URL}
    depends_on:
      - server
      - fcrepo
      - elasticsearch
    command: node service

volumes:
  fedora-data:
    driver: local
  fedora-serialized-data:
    driver: local
  es-data:
    driver: local
  redis-data:
    driver: local