
version: '2'

###
# Prod
###
services:

  ###
  # Font End NodeJS Application Server & Proxy
  ###
  server:
    build: ../../server
    volumes:
      - ../../services/frames:/etc/fin/frames
      - ../../services/default-services.js:/etc/fin/default-services.js
      - ../webapp-service-account.json:/etc/fin/webapp-service-account.json
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - FIN_URL=${FIN_URL}
    ports:
      - 3000:3001

  ###
  # Fedora Repository
  ###
  fcrepo:
    build: ../../fcrepo
    volumes:
      - fedora-data:/var/lib/jetty/fedora-data
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - FIN_URL=${FIN_URL}

  ###
  # UC DAMS Client UI
  ###
  ucd-lib-client:
    build: ../../services/ucd-lib-client
    volumes:
      - ../webapp-service-account.json:/etc/fin/webapp-service-account.json
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - FIN_URL=${FIN_URL}
      - FIN_ENV=prod
    depends_on:
      - elasticsearch

  ###
  # Search
  ###
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ../elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    depends_on:
      - server

  ###
  # Session, local user and role store
  ###
  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data
    depends_on:
      - fcrepo  

  ###
  # Trusted Proxy for Services
  ###
  trustedproxy:
    build: ../../services/trusted-proxy
    volumes:
      - ../webapp-service-account.json:/etc/fin/webapp-service-account.json
    depends_on:
      - fcrepo
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}

  ###
  # API Extension Services
  ###

  # iiif server
  loris:
    build: ../../services/loris
    depends_on:
      - fcrepo
    volumes:
      - loris-data:/usr/local/share/images/loris

  # elastic search indexer
  essync:
    build: ../../services/essync
    volumes:
      - ../webapp-service-account.json:/etc/fin/webapp-service-account.json
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - FIN_URL=${FIN_URL}
    depends_on:
      - server
      - fcrepo
      - elasticsearch

  # auto generator service demo
  auto-generator-demo:
    build: ../../services/auto-generator-demo
    volumes:
      - ../webapp-service-account.json:/etc/fin/webapp-service-account.json
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - FIN_URL=${FIN_URL}
    depends_on:
      - server
    # command: bash -c "tail -f /dev/null"

  ###
  # CAS AuthenticationService
  ###
  cas:
    build: ../../services/cas
    volumes:
      - ../webapp-service-account.json:/etc/fin/webapp-service-account.json
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - FIN_URL=${FIN_URL}
    depends_on:
      - server

  ###
  # Basic Username/Password AuthenticationService
  ###
  basic-auth:
    build: ../../services/basic-auth
    volumes:
      - ../webapp-service-account.json:/etc/fin/webapp-service-account.json
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - FIN_URL=${FIN_URL}
    depends_on:
      - server

volumes:
  fedora-data:
    driver: local
  es-data:
    driver: local
  redis-data:
    driver: local
  loris-data:
    driver: local