
version: '2'

###
# Dev
###
services:
  
  ###
  # Font End NodeJS Application Server & Proxy
  ###
  server:
    build: ../../server
    volumes:
      - ../../server/cli:/app/cli
      - ../../server/controllers:/app/controllers
      - ../../server/lib:/app/lib
      - ../../server/models:/app/models
      - ../../server/default-frames:/etc/fin/frames
      - ../../server/default-transforms:/etc/fin/transforms
      - ../../services/default-services.js:/etc/fin/default-services.js
      - ../webapp-service-account.json:/etc/fin/webapp-service-account.json
      - ../../server/backups:/fcrepo-backups
    ports:
      - 3000:3001
      - 9229:9229
    # command: tail -f /dev/null
    command: node app
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - FIN_URL=${FIN_URL}
      - FIN_ENV=dev
      - FIN_ALLOW_ORIGINS=localhost:8081

  # postgres:
  #   image: postgres:9
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - pg-data:/var/lib/postgresql/data

  ###
  # Fedora Repository
  ###
  fcrepo:
    build: ../../fcrepo
    volumes:
      - fedora-data:/var/lib/jetty/fedora-data
      - ../../server/backups:/var/lib/jetty/fcrepo-backups
      - ../webapp-service-account.json:/etc/fin/webapp-service-account.json
    ports:
      - 8080:8080
      - 61613:61613
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_VERBOSE=${JWT_VERBOSE}
      - FIN_URL=${FIN_URL}

  ###
  # Search
  ###
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # mem_limit: 1g
    # for docker-compose version 3
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1g
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ../elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    depends_on:
      - fcrepo
  
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:5.4.1
  #   depends_on:
  #     - elasticsearch
  #   # volumes: 
  #   #   - ../kibana.yml:/usr/share/kibana/config/kibana.yml
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch:9200
  #   ports:
  #     - 5601:5601
  #   command: bash -c 'sleep 30 && /usr/local/bin/kibana-docker'
  
  ###
  # Session, local user and role store
  ###
  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    depends_on:
      - fcrepo

  ###
  # Trusted Proxy for Services
  ###
  trustedproxy:
    build: ../../services/trusted-proxy
    volumes:
      - ../../services/trusted-proxy/index.js:/service/index.js
      - ../webapp-service-account.json:/etc/fin/webapp-service-account.json
    depends_on:
      - fcrepo
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_TTL=${JWT_TTL}
    command: node service

  ###
  # API Extension Services
  ###
  loris:
    build: ../../services/loris
    volumes:
      - loris-data:/usr/local/share/images/loris
      - ../../services/loris/loris2.conf:/opt/loris/etc/loris2.conf
      - ../../services/loris/start.py:/opt/loris/loris/start.py
    depends_on:
      - fcrepo

  # apixdemo:
  #   build: ../../apix-demo
  #   depends_on:
  #     - fcrepo
  
  ###
  # Services
  ###
  essync:
    build: ../../services/essync
    volumes:
      - ../../services/essync/lib:/service/lib
      - ../../services/essync/schemas:/service/schemas
      - ../../services/essync/index.js:/service/index.js
      - ../../services/essync/reindex.js:/service/reindex.js
      - ../webapp-service-account.json:/etc/fin/webapp-service-account.json
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - FIN_URL=${FIN_URL}
    depends_on:
      - server
    command: node service
    # command: bash -c 'tail -f /dev/null'

  tesseract:
    build: ../../services/tesseract
    volumes:
      - ../../services/tesseract/index.js:/service/index.js
      - ../webapp-service-account.json:/etc/fin/webapp-service-account.json
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - FIN_URL=${FIN_URL}
    depends_on:
      - server
    command: node service
    # command: bash -c 'tail -f /dev/null'

  auto-generator-demo:
    build: ../../services/auto-generator-demo
    volumes:
      - ../../services/auto-generator-demo/index.js:/service/index.js
      - ../webapp-service-account.json:/etc/fin/webapp-service-account.json
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - FIN_URL=${FIN_URL}
    depends_on:
      - server
    command: node service

  cas:
    build: ../../services/cas
    volumes:
      - ../../services/cas/controller.js:/service/controller.js
      - ../../services/cas/index.js:/service/index.js
      - ../webapp-service-account.json:/etc/fin/webapp-service-account.json
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - FIN_URL=${FIN_URL}
      - CAS_URL=https://ssodev.ucdavis.edu/cas
    depends_on:
      - server
    command: node service

  ucd-lib-client:
    build: ../../services/ucd-lib-client
    volumes:
      - ../../services/ucd-lib-client/index.js:/service/index.js
      - ../../services/ucd-lib-client/config.js:/service/config.js
      - ../../services/ucd-lib-client/client:/service/client
      - ../../services/ucd-lib-client/controllers:/service/controllers
      - ../../services/ucd-lib-client/lib:/service/lib
      - ../../services/ucd-lib-client/models:/service/models
      - ../webapp-service-account.json:/etc/fin/webapp-service-account.json
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - FIN_URL=${FIN_URL}
      #- FIN_ENV=prod
    depends_on:
      - server
    command: node service
    # command: bash -c 'tail -f /dev/null'

  basic-auth:
    build: ../../services/basic-auth
    volumes:
      - ../../services/basic-auth/index.js:/service/index.js
      - ../../services/basic-auth/cli.js:/service/cli.js
      - ../../services/basic-auth/controller.js:/service/controller.js
      - ../../services/basic-auth/model.js:/service/model.js
      - ../../services/basic-auth/lib:/service/lib
      - ../../services/basic-auth/public:/service/public
      - ../webapp-service-account.json:/etc/fin/webapp-service-account.json
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - FIN_URL=${FIN_URL}
    depends_on:
      - server
    command: node service

  # karafservices:
  #   build: ../../karafservices
  #   environment:
  #     - JWT_SECRET=${JWT_SECRET}
  #     - JWT_ISSUER=${JWT_ISSUER}
  #     - JWT_TTL=${JWT_TTL}
  #   extra_hosts:
  #     - "${FIN_HOST}:127.0.0.1"
  #   ports:
  #     - 1099:1099
  #     - 8101:8101 
  #     - 44444:44444
  #   volumes:
  #     - fedora-serialized-data:/data

volumes:
  fedora-data:
    driver: local
  es-data:
    driver: local
  redis-data:
    driver: local
  loris-data:
    driver: local
  pg-data:
    driver: local