
version: '2'

services:

  fcrepo:
    build: ../../fcrepo
    volumes:
      - fedora-data:/fedora-data
    ports:
      - 8080:8080
      - 61613:61613
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_COOKIE_NAME=${JWT_COOKIE_NAME}
      - JWT_VERBOSE=${JWT_VERBOSE}
      - DAMS_URL=${DAMS_URL}

  server:
    image: node:8.5
    volumes:
      - ../../server:/app
    ports:
      - 3001:3001
      - 9229:9229
    command: tail -f /dev/null
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_TTL=${JWT_TTL}
      - JWT_COOKIE_NAME=${JWT_COOKIE_NAME}
    depends_on:
      - fcrepo
      - elasticsearch
      - redis

  proxy:
    build: ../../proxy
    ports:
      - 3000:80
    depends_on:
      - server
      - fcrepo

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    # for docker-compose version 3
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1g
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    depends_on:
      - fcrepo
  
  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    depends_on:
      - fcrepo

volumes:
  fedora-data:
    driver: local
  es-data:
    driver: local
  redis-data:
    driver: local