
version: '2'

###
# Dev
###
services:
  
  ###
  # Font End NodeJS Application Server & Proxy
  ###
  server:
    build: ../../server
    volumes:
      - ../../server:/app
      - ../../services/frames:/etc/dams/frames
      - ../../services/default-services.js:/etc/dams/default-services.js
    ports:
      - 3000:3001
      - 9229:9229
    command: tail -f /dev/null
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_TTL=${JWT_TTL}
      - JWT_COOKIE_NAME=${JWT_COOKIE_NAME}
      - DAMS_URL=${DAMS_URL}
      - DAMS_ENV=dev
    depends_on:
      - fcrepo
      - elasticsearch
      - redis

  ###
  # Fedora Repository
  ###
  fcrepo:
    build: ../../fcrepo
    volumes:
      - fedora-data:/var/lib/jetty/fedora-data
    ports:
      - 8080:8080
      - 61613:61613
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_COOKIE_NAME=${JWT_COOKIE_NAME}
      - JWT_VERBOSE=${JWT_VERBOSE}
      - DAMS_URL=${DAMS_URL}

  ###
  # Search
  ###
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # mem_limit: 1g
    # for docker-compose version 3
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1g
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ../elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    depends_on:
      - fcrepo
  
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:5.4.1
  #   depends_on:
  #     - elasticsearch
  #   # volumes: 
  #   #   - ../kibana.yml:/usr/share/kibana/config/kibana.yml
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch:9200
  #   ports:
  #     - 5601:5601
  #   command: bash -c 'sleep 30 && /usr/local/bin/kibana-docker'
  
  ###
  # Session, local user and role store
  ###
  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    depends_on:
      - fcrepo

  ###
  # Trusted Proxy for Services
  ###
  trustedproxy:
    build: ../../services/trusted-proxy
    depends_on:
      - fcrepo
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_TTL=${JWT_TTL}

  ###
  # API Extension Services
  ###
  loris:
    build: ../../services/loris
    depends_on:
      - fcrepo

  # apixdemo:
  #   build: ../../apix-demo
  #   depends_on:
  #     - fcrepo
  
  ###
  # ActiveMQ Services
  ###
  essync:
    image: node:8.5
    volumes:
      - ../../services/essync:/service
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_TTL=${JWT_TTL}
      - DAMS_URL=${DAMS_URL}
    depends_on:
      - server
      - fcrepo
      - elasticsearch
    command: node service

  serialization:
    image: node:8.5
    volumes:
      - ../../services/serialization:/service
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_TTL=${JWT_TTL}
      - DAMS_URL=${DAMS_URL}
    depends_on:
      - server
      - fcrepo
      - elasticsearch
    command: node service

  cas:
    image: node:8
    volumes:
      - ../../services/cas:/service
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_TTL=${JWT_TTL}
      - DAMS_URL=${DAMS_URL}
    depends_on:
      - server
      - fcrepo
      - elasticsearch
    command: node service

  ucd-lib-client:
    image: node:8
    volumes:
      - ../../services/ucd-lib-client:/service
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_TTL=${JWT_TTL}
      - DAMS_URL=${DAMS_URL}
    depends_on:
      - server
      - fcrepo
      - elasticsearch
    command: node service

  # karafservices:
  #   build: ../../karafservices
  #   environment:
  #     - JWT_SECRET=${JWT_SECRET}
  #     - JWT_ISSUER=${JWT_ISSUER}
  #     - JWT_TTL=${JWT_TTL}
  #   extra_hosts:
  #     - "${DAMS_HOST}:127.0.0.1"
  #   ports:
  #     - 1099:1099
  #     - 8101:8101 
  #     - 44444:44444
  #   volumes:
  #     - fedora-serialized-data:/data

volumes:
  fedora-data:
    driver: local
  fedora-serialized-data:
    driver: local
  es-data:
    driver: local
  redis-data:
    driver: local