
version: '2'

services:

  fcrepo:
    build: ../../fcrepo
    volumes:
      - fedora-data:/var/lib/jetty/fedora-data
    ports:
      - 8080:8080
      - 61613:61613
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_COOKIE_NAME=${JWT_COOKIE_NAME}
      - JWT_VERBOSE=${JWT_VERBOSE}
      - DAMS_URL=${DAMS_URL}

  server:
    image: node:8.5
    volumes:
      - ../../server:/app
    ports:
      - 3001:3001
      - 9229:9229
    command: tail -f /dev/null
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_TTL=${JWT_TTL}
      - JWT_COOKIE_NAME=${JWT_COOKIE_NAME}
      - DAMS_URL=${DAMS_URL}
      - ACTIVEMQ_SERVICES=essync,serialization
    depends_on:
      - fcrepo
      - elasticsearch
      - redis

  proxy:
    build: ../../proxy
    ports:
      - 3000:80
    depends_on:
      - server
      - fcrepo
  
  essync:
    # build: ../../activemq/essync
    image: node:8.5
    volumes:
      - ../../activemq/essync:/service
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_TTL=${JWT_TTL}
    depends_on:
      - server
      - fcrepo
    command: node service

  serialization:
    # build: ../../activemq/serialization
    image: node:8.5
    volumes:
      - ../../activemq/serialization:/service
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_TTL=${JWT_TTL}
    depends_on:
      - server
      - fcrepo
    command: node service

  # karafservices:
  #   build: ../../karafservices
  #   environment:
  #     - JWT_SECRET=${JWT_SECRET}
  #     - JWT_ISSUER=${JWT_ISSUER}
  #     - JWT_TTL=${JWT_TTL}
  #   extra_hosts:
  #     - "${DAMS_HOST}:127.0.0.1"
  #   ports:
  #     - 1099:1099
  #     - 8101:8101 
  #     - 44444:44444
  #   volumes:
  #     - fedora-serialized-data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    # for docker-compose version 3
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1g
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ../elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    depends_on:
      - fcrepo
  
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:5.4.1
  #   depends_on:
  #     - elasticsearch
  #   # volumes: 
  #   #   - ../kibana.yml:/usr/share/kibana/config/kibana.yml
  #   environment:
  #     ELASTICSEARCH_URL: http://elasticsearch:9200
  #   ports:
  #     - 5601:5601
  
  redis:
    image: redis:3.2
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    depends_on:
      - fcrepo

  loris:
    build: ../../loris
    depends_on:
      - fcrepo

volumes:
  fedora-data:
    driver: local
  fedora-serialized-data:
    driver: local
  es-data:
    driver: local
  redis-data:
    driver: local